steps:
- name: "gcr.io/cloud-builders/yarn"
  args: ["install"]

- name: "gcr.io/cloud-builders/yarn"
  args: ["build"]

- name: gcr.io/cloud-builders/git
  args: ['clone', 'https://source.developers.google.com/p/$PROJECT_ID/r/${_API_REPOSITORY}']

- name: "ubuntu"
  entrypoint: 'mkdir'
  args: ["${_API_REPOSITORY}/dist"]

- name: "ubuntu"
  entrypoint: 'cp'
  args: ["$REPO_NAME/build/", "${_API_REPOSITORY}/public"]

- name: "gcr.io/cloud-builders/gcloud"
  args: ["app", "deploy"]
  dir: '${_API_REPOSITORY}/'
timeout: "1600s"